name: autofile-env

channels:
    - kevinmooreiii

dependencies:
    - python=3.7
    - numpy
    - pytest
    - pytest-cov
    - flake8
    - pylint
    - kevinmooreiii::automol
    - kevinmooreiii::autoparse
    - auto-mech::x2z
