name: autofile-env

channels:
    - kevinmooreiii
    - auto-mech
    - rdkit
    - openbabel
    - conda-forge

dependencies:
    - python=3.7
    - numpy
    - pyyaml
    - pytest
    - pytest-cov
    - flake8
    - pylint
    - kevinmooreiii::automol
    - kevinmooreiii::autoparse
    - auto-mech::x2z
    - rdkit::rdkit
    - openbabel::openbabel
    - conda-forge::qcelemental
