# cmd: conda build . -c kevinmooreiii -c auto-mech -c rdkit -c openbabel -c conda-forge
package:
    name: autofile
    version: "0.1.0"

source:
    path: .

requirements:
    build:
        - python
    run:
        - python
        - numpy
        - pyyaml
        - pytest
        - pytest-cov
        - flake8
        - pylint
        - kevinmooreiii::autoparse
        - auto-mech::x2z
        - rdkit::rdkit
        - openbabel::openbabel
        - conda-forge::qcelemental
