# cmd: conda build . -c kevinmooreiii -c auto-mech
package:
    name: autofile
    version: "0.1.0"

source:
    path: .

requirements:
    build:
        - python
    run:
        - python
        - numpy
        - pyyaml
        - pytest
        - pytest-cov
        - flake8
        - pylint
        - kevinmooreiii::autoparse
        - kevinmooreiii::automol
        - auto-mech::x2z
