# cmd: conda build .
package:
    name: autofile
    version: "0.1.0"

source:
    path: .

requirements:
    build:
        - python
    run:
        - python
        - numpy
        - pyyaml
        - pytest
        - pytest-cov
        - flake8
        - pylint
