package:
  name: autofile
  version: "2024.6.4"

about:
  license: MIT
  description: Filesystem database manager for AutoMech
  repository: https://github.com/Auto-Mech/autofile

source:
  path: .

build:
  noarch: python
  script: pip install . -v --no-deps

requirements:
  host:
    - pip
    - python >=3.10
    - poetry
    - wheel
  run:
    - python >=3.10
    - pip
    - numpy
    - pylint
    - pytest
    - pyyaml
    - auto-mech::autochem
    - auto-mech::autoio
