version: 2
jobs:
    build-debian:
        docker:
            - image: continuumio/miniconda3
        steps:
            - checkout  # checkout the code
            - run: 
                name: Create conda environment
                command: |
                    apt-get update --yes
                    apt-get install --yes libxrender-dev build-essential
                    conda env create -f environment.yml
            - run:
                name: Build/install autofile
                command: |
                    source activate autofile-env
                    python setup.py install
            - run:
                name: Test autofile
                command: |
                    source activate autofile-env
                    pwd
                    cd autofile
                    pwd
                    pytest -v --disable-pytest-warnings --cov=autofile --pyargs autofile --cov-report=html
                    coverage report
            - run:
                name: pylint autofile
                command: |
                    source activate autofile-env
                    cd autofile
                    flake8 --exit-zero ../autofile
                    pylint --rcfile=../.pylintrc autofile
            - store_artifacts:
                    path: autofile/htmlcov
workflows:
    version: 2
    build-all:
        jobs:
            - build-and-test-autofile
